/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IVRFConsumer } from "./IVRFConsumer";
export type { MockVRFCoordinatorV2Plus } from "./MockVRFCoordinatorV2Plus";
