/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export declare namespace VRFV2PlusClient {
  export type RandomWordsRequestStruct = {
    keyHash: BytesLike;
    subId: BigNumberish;
    requestConfirmations: BigNumberish;
    callbackGasLimit: BigNumberish;
    numWords: BigNumberish;
    extraArgs: BytesLike;
  };

  export type RandomWordsRequestStructOutput = [
    keyHash: string,
    subId: bigint,
    requestConfirmations: bigint,
    callbackGasLimit: bigint,
    numWords: bigint,
    extraArgs: string
  ] & {
    keyHash: string;
    subId: bigint;
    requestConfirmations: bigint;
    callbackGasLimit: bigint;
    numWords: bigint;
    extraArgs: string;
  };
}

export interface MockVRFCoordinatorV2PlusInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "fulfillRandomWordsWithOverride"
      | "lastRequestId"
      | "requestRandomWords"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "RandomWordsRequested"): EventFragment;

  encodeFunctionData(
    functionFragment: "fulfillRandomWordsWithOverride",
    values: [BigNumberish, AddressLike, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "lastRequestId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestRandomWords",
    values: [VRFV2PlusClient.RandomWordsRequestStruct]
  ): string;

  decodeFunctionResult(
    functionFragment: "fulfillRandomWordsWithOverride",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastRequestId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestRandomWords",
    data: BytesLike
  ): Result;
}

export namespace RandomWordsRequestedEvent {
  export type InputTuple = [requestId: BigNumberish, consumer: AddressLike];
  export type OutputTuple = [requestId: bigint, consumer: string];
  export interface OutputObject {
    requestId: bigint;
    consumer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MockVRFCoordinatorV2Plus extends BaseContract {
  connect(runner?: ContractRunner | null): MockVRFCoordinatorV2Plus;
  waitForDeployment(): Promise<this>;

  interface: MockVRFCoordinatorV2PlusInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  fulfillRandomWordsWithOverride: TypedContractMethod<
    [requestId: BigNumberish, consumer: AddressLike, words: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  lastRequestId: TypedContractMethod<[], [bigint], "view">;

  requestRandomWords: TypedContractMethod<
    [arg0: VRFV2PlusClient.RandomWordsRequestStruct],
    [bigint],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "fulfillRandomWordsWithOverride"
  ): TypedContractMethod<
    [requestId: BigNumberish, consumer: AddressLike, words: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "lastRequestId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "requestRandomWords"
  ): TypedContractMethod<
    [arg0: VRFV2PlusClient.RandomWordsRequestStruct],
    [bigint],
    "nonpayable"
  >;

  getEvent(
    key: "RandomWordsRequested"
  ): TypedContractEvent<
    RandomWordsRequestedEvent.InputTuple,
    RandomWordsRequestedEvent.OutputTuple,
    RandomWordsRequestedEvent.OutputObject
  >;

  filters: {
    "RandomWordsRequested(uint256,address)": TypedContractEvent<
      RandomWordsRequestedEvent.InputTuple,
      RandomWordsRequestedEvent.OutputTuple,
      RandomWordsRequestedEvent.OutputObject
    >;
    RandomWordsRequested: TypedContractEvent<
      RandomWordsRequestedEvent.InputTuple,
      RandomWordsRequestedEvent.OutputTuple,
      RandomWordsRequestedEvent.OutputObject
    >;
  };
}
