/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IVRFConsumer,
  IVRFConsumerInterface,
} from "../../../../contracts/test/MockVRFCoordinatorV2Plus.sol/IVRFConsumer";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "requestId",
        type: "uint256",
      },
      {
        internalType: "uint256[]",
        name: "randomWords",
        type: "uint256[]",
      },
    ],
    name: "rawFulfillRandomWords",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IVRFConsumer__factory {
  static readonly abi = _abi;
  static createInterface(): IVRFConsumerInterface {
    return new Interface(_abi) as IVRFConsumerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IVRFConsumer {
    return new Contract(address, _abi, runner) as unknown as IVRFConsumer;
  }
}
