/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mockVrfCoordinatorV2PlusSol from "./MockVRFCoordinatorV2Plus.sol";
export type { mockVrfCoordinatorV2PlusSol };
export type { MockERC721 } from "./MockERC721";
