/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace BindrGachaV2 {
  export type InitConfigStruct = {
    nft: AddressLike;
    initialVault: AddressLike;
    initialBackend: AddressLike;
    initialPauseGuardian: AddressLike;
    vrfCoordinator: AddressLike;
    vrfKeyHash: BytesLike;
    vrfSubscriptionId: BigNumberish;
    vrfNativePayment: boolean;
    callbackGasLimit: BigNumberish;
    requestConfirmations: BigNumberish;
    minPullIntervalBlocks: BigNumberish;
    maxPullsPerBlock: BigNumberish;
  };

  export type InitConfigStructOutput = [
    nft: string,
    initialVault: string,
    initialBackend: string,
    initialPauseGuardian: string,
    vrfCoordinator: string,
    vrfKeyHash: string,
    vrfSubscriptionId: bigint,
    vrfNativePayment: boolean,
    callbackGasLimit: bigint,
    requestConfirmations: bigint,
    minPullIntervalBlocks: bigint,
    maxPullsPerBlock: bigint
  ] & {
    nft: string;
    initialVault: string;
    initialBackend: string;
    initialPauseGuardian: string;
    vrfCoordinator: string;
    vrfKeyHash: string;
    vrfSubscriptionId: bigint;
    vrfNativePayment: boolean;
    callbackGasLimit: bigint;
    requestConfirmations: bigint;
    minPullIntervalBlocks: bigint;
    maxPullsPerBlock: bigint;
  };
}

export interface BindrGachaV2Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "NFT"
      | "NUM_BUCKETS"
      | "NUM_PACK_TIERS"
      | "VRF_KEY_HASH"
      | "VRF_NATIVE_PAYMENT"
      | "VRF_SUBSCRIPTION_ID"
      | "WEIGHT_TOTAL_BPS"
      | "acceptOwnership"
      | "addCards"
      | "availableInBucket"
      | "availableInPack"
      | "backendSigner"
      | "callbackGasLimit"
      | "cancelPendingPull"
      | "cards"
      | "claimPending"
      | "emergencyPause"
      | "getBucketWeights"
      | "giveaway"
      | "isVaultReady"
      | "lastPullBlock"
      | "maxPullsPerBlock"
      | "minPullIntervalBlocks"
      | "owner"
      | "pauseGuardian"
      | "paused"
      | "pendingPulls"
      | "polygonGiveawayUsed"
      | "pullsInBlock"
      | "rawFulfillRandomWords"
      | "removeCard"
      | "requestConfirmations"
      | "requestPull"
      | "s_vrfCoordinator"
      | "setBackendSigner"
      | "setBucketWeights"
      | "setCoordinator"
      | "setPauseGuardian"
      | "setRateLimits"
      | "setVault"
      | "setVrfConfig"
      | "solanaGiveawayUsed"
      | "transferOwnership"
      | "unpause"
      | "usedBurnProofs"
      | "vault"
      | "withdrawCard"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BackendSignerChanged"
      | "CardAdded"
      | "CardRemoved"
      | "CardWithdrawn"
      | "CoordinatorSet"
      | "Giveaway"
      | "OwnershipTransferRequested"
      | "OwnershipTransferred"
      | "PauseGuardianChanged"
      | "Paused"
      | "PullAwaitingClaim"
      | "PullCancelled"
      | "PullClaimed"
      | "PullRequested"
      | "Pulled"
      | "RateLimitsUpdated"
      | "Unpaused"
      | "VaultChanged"
      | "VrfConfigUpdated"
      | "WeightsUpdated"
  ): EventFragment;

  encodeFunctionData(functionFragment: "NFT", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "NUM_BUCKETS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "NUM_PACK_TIERS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VRF_KEY_HASH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VRF_NATIVE_PAYMENT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VRF_SUBSCRIPTION_ID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "WEIGHT_TOTAL_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "acceptOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addCards",
    values: [BigNumberish, BigNumberish[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "availableInBucket",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "availableInPack",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "backendSigner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "callbackGasLimit",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cancelPendingPull",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cards",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimPending",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyPause",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBucketWeights",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "giveaway",
    values: [AddressLike, BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isVaultReady",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastPullBlock",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "maxPullsPerBlock",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "minPullIntervalBlocks",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pauseGuardian",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingPulls",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "polygonGiveawayUsed",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "pullsInBlock",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "rawFulfillRandomWords",
    values: [BigNumberish, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "removeCard",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "requestConfirmations",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestPull",
    values: [AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "s_vrfCoordinator",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setBackendSigner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setBucketWeights",
    values: [BigNumberish, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "setCoordinator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setPauseGuardian",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setRateLimits",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setVault",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setVrfConfig",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "solanaGiveawayUsed",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "usedBurnProofs",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "vault", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdrawCard",
    values: [BigNumberish, BigNumberish, AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "NFT", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "NUM_BUCKETS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "NUM_PACK_TIERS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VRF_KEY_HASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VRF_NATIVE_PAYMENT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VRF_SUBSCRIPTION_ID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "WEIGHT_TOTAL_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "acceptOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addCards", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "availableInBucket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "availableInPack",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "backendSigner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "callbackGasLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelPendingPull",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "cards", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimPending",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyPause",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBucketWeights",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "giveaway", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isVaultReady",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastPullBlock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxPullsPerBlock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minPullIntervalBlocks",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pauseGuardian",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingPulls",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "polygonGiveawayUsed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pullsInBlock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rawFulfillRandomWords",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "removeCard", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "requestConfirmations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestPull",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "s_vrfCoordinator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBackendSigner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBucketWeights",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCoordinator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPauseGuardian",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRateLimits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setVault", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setVrfConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "solanaGiveawayUsed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "usedBurnProofs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vault", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawCard",
    data: BytesLike
  ): Result;
}

export namespace BackendSignerChangedEvent {
  export type InputTuple = [previous: AddressLike, current: AddressLike];
  export type OutputTuple = [previous: string, current: string];
  export interface OutputObject {
    previous: string;
    current: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CardAddedEvent {
  export type InputTuple = [
    packTier: BigNumberish,
    tokenId: BigNumberish,
    bucket: BigNumberish
  ];
  export type OutputTuple = [packTier: bigint, tokenId: bigint, bucket: bigint];
  export interface OutputObject {
    packTier: bigint;
    tokenId: bigint;
    bucket: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CardRemovedEvent {
  export type InputTuple = [packTier: BigNumberish, tokenId: BigNumberish];
  export type OutputTuple = [packTier: bigint, tokenId: bigint];
  export interface OutputObject {
    packTier: bigint;
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CardWithdrawnEvent {
  export type InputTuple = [
    packTier: BigNumberish,
    tokenId: BigNumberish,
    to: AddressLike
  ];
  export type OutputTuple = [packTier: bigint, tokenId: bigint, to: string];
  export interface OutputObject {
    packTier: bigint;
    tokenId: bigint;
    to: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CoordinatorSetEvent {
  export type InputTuple = [vrfCoordinator: AddressLike];
  export type OutputTuple = [vrfCoordinator: string];
  export interface OutputObject {
    vrfCoordinator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GiveawayEvent {
  export type InputTuple = [
    user: AddressLike,
    packTier: BigNumberish,
    tokenId: BigNumberish,
    bucket: BigNumberish,
    solanaHash: BytesLike
  ];
  export type OutputTuple = [
    user: string,
    packTier: bigint,
    tokenId: bigint,
    bucket: bigint,
    solanaHash: string
  ];
  export interface OutputObject {
    user: string;
    packTier: bigint;
    tokenId: bigint;
    bucket: bigint;
    solanaHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferRequestedEvent {
  export type InputTuple = [from: AddressLike, to: AddressLike];
  export type OutputTuple = [from: string, to: string];
  export interface OutputObject {
    from: string;
    to: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [from: AddressLike, to: AddressLike];
  export type OutputTuple = [from: string, to: string];
  export interface OutputObject {
    from: string;
    to: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PauseGuardianChangedEvent {
  export type InputTuple = [previous: AddressLike, current: AddressLike];
  export type OutputTuple = [previous: string, current: string];
  export interface OutputObject {
    previous: string;
    current: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PullAwaitingClaimEvent {
  export type InputTuple = [
    requestId: BigNumberish,
    user: AddressLike,
    tokenId: BigNumberish,
    bucket: BigNumberish,
    reason: BytesLike
  ];
  export type OutputTuple = [
    requestId: bigint,
    user: string,
    tokenId: bigint,
    bucket: bigint,
    reason: string
  ];
  export interface OutputObject {
    requestId: bigint;
    user: string;
    tokenId: bigint;
    bucket: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PullCancelledEvent {
  export type InputTuple = [
    requestId: BigNumberish,
    user: AddressLike,
    burnProof: BytesLike,
    packTier: BigNumberish
  ];
  export type OutputTuple = [
    requestId: bigint,
    user: string,
    burnProof: string,
    packTier: bigint
  ];
  export interface OutputObject {
    requestId: bigint;
    user: string;
    burnProof: string;
    packTier: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PullClaimedEvent {
  export type InputTuple = [
    requestId: BigNumberish,
    to: AddressLike,
    tokenId: BigNumberish
  ];
  export type OutputTuple = [requestId: bigint, to: string, tokenId: bigint];
  export interface OutputObject {
    requestId: bigint;
    to: string;
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PullRequestedEvent {
  export type InputTuple = [
    requestId: BigNumberish,
    user: AddressLike,
    packTier: BigNumberish,
    burnProof: BytesLike
  ];
  export type OutputTuple = [
    requestId: bigint,
    user: string,
    packTier: bigint,
    burnProof: string
  ];
  export interface OutputObject {
    requestId: bigint;
    user: string;
    packTier: bigint;
    burnProof: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PulledEvent {
  export type InputTuple = [
    requestId: BigNumberish,
    user: AddressLike,
    packTier: BigNumberish,
    tokenId: BigNumberish,
    bucket: BigNumberish,
    burnProof: BytesLike
  ];
  export type OutputTuple = [
    requestId: bigint,
    user: string,
    packTier: bigint,
    tokenId: bigint,
    bucket: bigint,
    burnProof: string
  ];
  export interface OutputObject {
    requestId: bigint;
    user: string;
    packTier: bigint;
    tokenId: bigint;
    bucket: bigint;
    burnProof: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RateLimitsUpdatedEvent {
  export type InputTuple = [
    minPullIntervalBlocks: BigNumberish,
    maxPullsPerBlock: BigNumberish
  ];
  export type OutputTuple = [
    minPullIntervalBlocks: bigint,
    maxPullsPerBlock: bigint
  ];
  export interface OutputObject {
    minPullIntervalBlocks: bigint;
    maxPullsPerBlock: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VaultChangedEvent {
  export type InputTuple = [previous: AddressLike, current: AddressLike];
  export type OutputTuple = [previous: string, current: string];
  export interface OutputObject {
    previous: string;
    current: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VrfConfigUpdatedEvent {
  export type InputTuple = [
    callbackGasLimit: BigNumberish,
    requestConfirmations: BigNumberish
  ];
  export type OutputTuple = [
    callbackGasLimit: bigint,
    requestConfirmations: bigint
  ];
  export interface OutputObject {
    callbackGasLimit: bigint;
    requestConfirmations: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WeightsUpdatedEvent {
  export type InputTuple = [packTier: BigNumberish, weights: BigNumberish[]];
  export type OutputTuple = [packTier: bigint, weights: bigint[]];
  export interface OutputObject {
    packTier: bigint;
    weights: bigint[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BindrGachaV2 extends BaseContract {
  connect(runner?: ContractRunner | null): BindrGachaV2;
  waitForDeployment(): Promise<this>;

  interface: BindrGachaV2Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  NFT: TypedContractMethod<[], [string], "view">;

  NUM_BUCKETS: TypedContractMethod<[], [bigint], "view">;

  NUM_PACK_TIERS: TypedContractMethod<[], [bigint], "view">;

  VRF_KEY_HASH: TypedContractMethod<[], [string], "view">;

  VRF_NATIVE_PAYMENT: TypedContractMethod<[], [boolean], "view">;

  VRF_SUBSCRIPTION_ID: TypedContractMethod<[], [bigint], "view">;

  WEIGHT_TOTAL_BPS: TypedContractMethod<[], [bigint], "view">;

  acceptOwnership: TypedContractMethod<[], [void], "nonpayable">;

  addCards: TypedContractMethod<
    [packTier: BigNumberish, tokenIds: BigNumberish[], buckets: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  availableInBucket: TypedContractMethod<
    [packTier: BigNumberish, bucket: BigNumberish],
    [bigint],
    "view"
  >;

  availableInPack: TypedContractMethod<
    [packTier: BigNumberish],
    [bigint],
    "view"
  >;

  backendSigner: TypedContractMethod<[], [string], "view">;

  callbackGasLimit: TypedContractMethod<[], [bigint], "view">;

  cancelPendingPull: TypedContractMethod<
    [requestId: BigNumberish],
    [void],
    "nonpayable"
  >;

  cards: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [[bigint, boolean] & { bucket: bigint; available: boolean }],
    "view"
  >;

  claimPending: TypedContractMethod<
    [requestId: BigNumberish, to: AddressLike],
    [void],
    "nonpayable"
  >;

  emergencyPause: TypedContractMethod<[], [void], "nonpayable">;

  getBucketWeights: TypedContractMethod<
    [packTier: BigNumberish],
    [bigint[]],
    "view"
  >;

  giveaway: TypedContractMethod<
    [
      user: AddressLike,
      solanaHash: BytesLike,
      packTier: BigNumberish,
      tokenId: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  isVaultReady: TypedContractMethod<[], [boolean], "view">;

  lastPullBlock: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  maxPullsPerBlock: TypedContractMethod<[], [bigint], "view">;

  minPullIntervalBlocks: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pauseGuardian: TypedContractMethod<[], [string], "view">;

  paused: TypedContractMethod<[], [boolean], "view">;

  pendingPulls: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        bigint,
        string,
        bigint,
        boolean,
        boolean,
        string,
        bigint,
        bigint,
        boolean
      ] & {
        user: string;
        packTier: bigint;
        burnProof: string;
        timestamp: bigint;
        fulfilled: boolean;
        cancelled: boolean;
        vaultAtRequest: string;
        awaitingClaimTokenId: bigint;
        awaitingClaimBucket: bigint;
        awaitingClaim: boolean;
      }
    ],
    "view"
  >;

  polygonGiveawayUsed: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  pullsInBlock: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  rawFulfillRandomWords: TypedContractMethod<
    [requestId: BigNumberish, randomWords: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  removeCard: TypedContractMethod<
    [packTier: BigNumberish, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  requestConfirmations: TypedContractMethod<[], [bigint], "view">;

  requestPull: TypedContractMethod<
    [user: AddressLike, packTier: BigNumberish, burnProof: BytesLike],
    [bigint],
    "nonpayable"
  >;

  s_vrfCoordinator: TypedContractMethod<[], [string], "view">;

  setBackendSigner: TypedContractMethod<
    [newSigner: AddressLike],
    [void],
    "nonpayable"
  >;

  setBucketWeights: TypedContractMethod<
    [packTier: BigNumberish, weights: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  setCoordinator: TypedContractMethod<
    [_vrfCoordinator: AddressLike],
    [void],
    "nonpayable"
  >;

  setPauseGuardian: TypedContractMethod<
    [newGuardian: AddressLike],
    [void],
    "nonpayable"
  >;

  setRateLimits: TypedContractMethod<
    [newMinPullIntervalBlocks: BigNumberish, newMaxPullsPerBlock: BigNumberish],
    [void],
    "nonpayable"
  >;

  setVault: TypedContractMethod<[newVault: AddressLike], [void], "nonpayable">;

  setVrfConfig: TypedContractMethod<
    [newCallbackGasLimit: BigNumberish, newRequestConfirmations: BigNumberish],
    [void],
    "nonpayable"
  >;

  solanaGiveawayUsed: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  transferOwnership: TypedContractMethod<
    [to: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  usedBurnProofs: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  vault: TypedContractMethod<[], [string], "view">;

  withdrawCard: TypedContractMethod<
    [packTier: BigNumberish, tokenId: BigNumberish, to: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "NFT"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "NUM_BUCKETS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "NUM_PACK_TIERS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "VRF_KEY_HASH"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "VRF_NATIVE_PAYMENT"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "VRF_SUBSCRIPTION_ID"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "WEIGHT_TOTAL_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "acceptOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "addCards"
  ): TypedContractMethod<
    [packTier: BigNumberish, tokenIds: BigNumberish[], buckets: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "availableInBucket"
  ): TypedContractMethod<
    [packTier: BigNumberish, bucket: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "availableInPack"
  ): TypedContractMethod<[packTier: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "backendSigner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "callbackGasLimit"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "cancelPendingPull"
  ): TypedContractMethod<[requestId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "cards"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [[bigint, boolean] & { bucket: bigint; available: boolean }],
    "view"
  >;
  getFunction(
    nameOrSignature: "claimPending"
  ): TypedContractMethod<
    [requestId: BigNumberish, to: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "emergencyPause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getBucketWeights"
  ): TypedContractMethod<[packTier: BigNumberish], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "giveaway"
  ): TypedContractMethod<
    [
      user: AddressLike,
      solanaHash: BytesLike,
      packTier: BigNumberish,
      tokenId: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isVaultReady"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "lastPullBlock"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "maxPullsPerBlock"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "minPullIntervalBlocks"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pauseGuardian"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "pendingPulls"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        bigint,
        string,
        bigint,
        boolean,
        boolean,
        string,
        bigint,
        bigint,
        boolean
      ] & {
        user: string;
        packTier: bigint;
        burnProof: string;
        timestamp: bigint;
        fulfilled: boolean;
        cancelled: boolean;
        vaultAtRequest: string;
        awaitingClaimTokenId: bigint;
        awaitingClaimBucket: bigint;
        awaitingClaim: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "polygonGiveawayUsed"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "pullsInBlock"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "rawFulfillRandomWords"
  ): TypedContractMethod<
    [requestId: BigNumberish, randomWords: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "removeCard"
  ): TypedContractMethod<
    [packTier: BigNumberish, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requestConfirmations"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "requestPull"
  ): TypedContractMethod<
    [user: AddressLike, packTier: BigNumberish, burnProof: BytesLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "s_vrfCoordinator"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setBackendSigner"
  ): TypedContractMethod<[newSigner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setBucketWeights"
  ): TypedContractMethod<
    [packTier: BigNumberish, weights: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setCoordinator"
  ): TypedContractMethod<[_vrfCoordinator: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPauseGuardian"
  ): TypedContractMethod<[newGuardian: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setRateLimits"
  ): TypedContractMethod<
    [newMinPullIntervalBlocks: BigNumberish, newMaxPullsPerBlock: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setVault"
  ): TypedContractMethod<[newVault: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setVrfConfig"
  ): TypedContractMethod<
    [newCallbackGasLimit: BigNumberish, newRequestConfirmations: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "solanaGiveawayUsed"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[to: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usedBurnProofs"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "vault"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "withdrawCard"
  ): TypedContractMethod<
    [packTier: BigNumberish, tokenId: BigNumberish, to: AddressLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "BackendSignerChanged"
  ): TypedContractEvent<
    BackendSignerChangedEvent.InputTuple,
    BackendSignerChangedEvent.OutputTuple,
    BackendSignerChangedEvent.OutputObject
  >;
  getEvent(
    key: "CardAdded"
  ): TypedContractEvent<
    CardAddedEvent.InputTuple,
    CardAddedEvent.OutputTuple,
    CardAddedEvent.OutputObject
  >;
  getEvent(
    key: "CardRemoved"
  ): TypedContractEvent<
    CardRemovedEvent.InputTuple,
    CardRemovedEvent.OutputTuple,
    CardRemovedEvent.OutputObject
  >;
  getEvent(
    key: "CardWithdrawn"
  ): TypedContractEvent<
    CardWithdrawnEvent.InputTuple,
    CardWithdrawnEvent.OutputTuple,
    CardWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "CoordinatorSet"
  ): TypedContractEvent<
    CoordinatorSetEvent.InputTuple,
    CoordinatorSetEvent.OutputTuple,
    CoordinatorSetEvent.OutputObject
  >;
  getEvent(
    key: "Giveaway"
  ): TypedContractEvent<
    GiveawayEvent.InputTuple,
    GiveawayEvent.OutputTuple,
    GiveawayEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferRequested"
  ): TypedContractEvent<
    OwnershipTransferRequestedEvent.InputTuple,
    OwnershipTransferRequestedEvent.OutputTuple,
    OwnershipTransferRequestedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PauseGuardianChanged"
  ): TypedContractEvent<
    PauseGuardianChangedEvent.InputTuple,
    PauseGuardianChangedEvent.OutputTuple,
    PauseGuardianChangedEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "PullAwaitingClaim"
  ): TypedContractEvent<
    PullAwaitingClaimEvent.InputTuple,
    PullAwaitingClaimEvent.OutputTuple,
    PullAwaitingClaimEvent.OutputObject
  >;
  getEvent(
    key: "PullCancelled"
  ): TypedContractEvent<
    PullCancelledEvent.InputTuple,
    PullCancelledEvent.OutputTuple,
    PullCancelledEvent.OutputObject
  >;
  getEvent(
    key: "PullClaimed"
  ): TypedContractEvent<
    PullClaimedEvent.InputTuple,
    PullClaimedEvent.OutputTuple,
    PullClaimedEvent.OutputObject
  >;
  getEvent(
    key: "PullRequested"
  ): TypedContractEvent<
    PullRequestedEvent.InputTuple,
    PullRequestedEvent.OutputTuple,
    PullRequestedEvent.OutputObject
  >;
  getEvent(
    key: "Pulled"
  ): TypedContractEvent<
    PulledEvent.InputTuple,
    PulledEvent.OutputTuple,
    PulledEvent.OutputObject
  >;
  getEvent(
    key: "RateLimitsUpdated"
  ): TypedContractEvent<
    RateLimitsUpdatedEvent.InputTuple,
    RateLimitsUpdatedEvent.OutputTuple,
    RateLimitsUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;
  getEvent(
    key: "VaultChanged"
  ): TypedContractEvent<
    VaultChangedEvent.InputTuple,
    VaultChangedEvent.OutputTuple,
    VaultChangedEvent.OutputObject
  >;
  getEvent(
    key: "VrfConfigUpdated"
  ): TypedContractEvent<
    VrfConfigUpdatedEvent.InputTuple,
    VrfConfigUpdatedEvent.OutputTuple,
    VrfConfigUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "WeightsUpdated"
  ): TypedContractEvent<
    WeightsUpdatedEvent.InputTuple,
    WeightsUpdatedEvent.OutputTuple,
    WeightsUpdatedEvent.OutputObject
  >;

  filters: {
    "BackendSignerChanged(address,address)": TypedContractEvent<
      BackendSignerChangedEvent.InputTuple,
      BackendSignerChangedEvent.OutputTuple,
      BackendSignerChangedEvent.OutputObject
    >;
    BackendSignerChanged: TypedContractEvent<
      BackendSignerChangedEvent.InputTuple,
      BackendSignerChangedEvent.OutputTuple,
      BackendSignerChangedEvent.OutputObject
    >;

    "CardAdded(uint8,uint256,uint8)": TypedContractEvent<
      CardAddedEvent.InputTuple,
      CardAddedEvent.OutputTuple,
      CardAddedEvent.OutputObject
    >;
    CardAdded: TypedContractEvent<
      CardAddedEvent.InputTuple,
      CardAddedEvent.OutputTuple,
      CardAddedEvent.OutputObject
    >;

    "CardRemoved(uint8,uint256)": TypedContractEvent<
      CardRemovedEvent.InputTuple,
      CardRemovedEvent.OutputTuple,
      CardRemovedEvent.OutputObject
    >;
    CardRemoved: TypedContractEvent<
      CardRemovedEvent.InputTuple,
      CardRemovedEvent.OutputTuple,
      CardRemovedEvent.OutputObject
    >;

    "CardWithdrawn(uint8,uint256,address)": TypedContractEvent<
      CardWithdrawnEvent.InputTuple,
      CardWithdrawnEvent.OutputTuple,
      CardWithdrawnEvent.OutputObject
    >;
    CardWithdrawn: TypedContractEvent<
      CardWithdrawnEvent.InputTuple,
      CardWithdrawnEvent.OutputTuple,
      CardWithdrawnEvent.OutputObject
    >;

    "CoordinatorSet(address)": TypedContractEvent<
      CoordinatorSetEvent.InputTuple,
      CoordinatorSetEvent.OutputTuple,
      CoordinatorSetEvent.OutputObject
    >;
    CoordinatorSet: TypedContractEvent<
      CoordinatorSetEvent.InputTuple,
      CoordinatorSetEvent.OutputTuple,
      CoordinatorSetEvent.OutputObject
    >;

    "Giveaway(address,uint8,uint256,uint8,bytes32)": TypedContractEvent<
      GiveawayEvent.InputTuple,
      GiveawayEvent.OutputTuple,
      GiveawayEvent.OutputObject
    >;
    Giveaway: TypedContractEvent<
      GiveawayEvent.InputTuple,
      GiveawayEvent.OutputTuple,
      GiveawayEvent.OutputObject
    >;

    "OwnershipTransferRequested(address,address)": TypedContractEvent<
      OwnershipTransferRequestedEvent.InputTuple,
      OwnershipTransferRequestedEvent.OutputTuple,
      OwnershipTransferRequestedEvent.OutputObject
    >;
    OwnershipTransferRequested: TypedContractEvent<
      OwnershipTransferRequestedEvent.InputTuple,
      OwnershipTransferRequestedEvent.OutputTuple,
      OwnershipTransferRequestedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PauseGuardianChanged(address,address)": TypedContractEvent<
      PauseGuardianChangedEvent.InputTuple,
      PauseGuardianChangedEvent.OutputTuple,
      PauseGuardianChangedEvent.OutputObject
    >;
    PauseGuardianChanged: TypedContractEvent<
      PauseGuardianChangedEvent.InputTuple,
      PauseGuardianChangedEvent.OutputTuple,
      PauseGuardianChangedEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "PullAwaitingClaim(uint256,address,uint256,uint8,bytes32)": TypedContractEvent<
      PullAwaitingClaimEvent.InputTuple,
      PullAwaitingClaimEvent.OutputTuple,
      PullAwaitingClaimEvent.OutputObject
    >;
    PullAwaitingClaim: TypedContractEvent<
      PullAwaitingClaimEvent.InputTuple,
      PullAwaitingClaimEvent.OutputTuple,
      PullAwaitingClaimEvent.OutputObject
    >;

    "PullCancelled(uint256,address,bytes32,uint8)": TypedContractEvent<
      PullCancelledEvent.InputTuple,
      PullCancelledEvent.OutputTuple,
      PullCancelledEvent.OutputObject
    >;
    PullCancelled: TypedContractEvent<
      PullCancelledEvent.InputTuple,
      PullCancelledEvent.OutputTuple,
      PullCancelledEvent.OutputObject
    >;

    "PullClaimed(uint256,address,uint256)": TypedContractEvent<
      PullClaimedEvent.InputTuple,
      PullClaimedEvent.OutputTuple,
      PullClaimedEvent.OutputObject
    >;
    PullClaimed: TypedContractEvent<
      PullClaimedEvent.InputTuple,
      PullClaimedEvent.OutputTuple,
      PullClaimedEvent.OutputObject
    >;

    "PullRequested(uint256,address,uint8,bytes32)": TypedContractEvent<
      PullRequestedEvent.InputTuple,
      PullRequestedEvent.OutputTuple,
      PullRequestedEvent.OutputObject
    >;
    PullRequested: TypedContractEvent<
      PullRequestedEvent.InputTuple,
      PullRequestedEvent.OutputTuple,
      PullRequestedEvent.OutputObject
    >;

    "Pulled(uint256,address,uint8,uint256,uint8,bytes32)": TypedContractEvent<
      PulledEvent.InputTuple,
      PulledEvent.OutputTuple,
      PulledEvent.OutputObject
    >;
    Pulled: TypedContractEvent<
      PulledEvent.InputTuple,
      PulledEvent.OutputTuple,
      PulledEvent.OutputObject
    >;

    "RateLimitsUpdated(uint256,uint8)": TypedContractEvent<
      RateLimitsUpdatedEvent.InputTuple,
      RateLimitsUpdatedEvent.OutputTuple,
      RateLimitsUpdatedEvent.OutputObject
    >;
    RateLimitsUpdated: TypedContractEvent<
      RateLimitsUpdatedEvent.InputTuple,
      RateLimitsUpdatedEvent.OutputTuple,
      RateLimitsUpdatedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;

    "VaultChanged(address,address)": TypedContractEvent<
      VaultChangedEvent.InputTuple,
      VaultChangedEvent.OutputTuple,
      VaultChangedEvent.OutputObject
    >;
    VaultChanged: TypedContractEvent<
      VaultChangedEvent.InputTuple,
      VaultChangedEvent.OutputTuple,
      VaultChangedEvent.OutputObject
    >;

    "VrfConfigUpdated(uint32,uint16)": TypedContractEvent<
      VrfConfigUpdatedEvent.InputTuple,
      VrfConfigUpdatedEvent.OutputTuple,
      VrfConfigUpdatedEvent.OutputObject
    >;
    VrfConfigUpdated: TypedContractEvent<
      VrfConfigUpdatedEvent.InputTuple,
      VrfConfigUpdatedEvent.OutputTuple,
      VrfConfigUpdatedEvent.OutputObject
    >;

    "WeightsUpdated(uint8,uint16[6])": TypedContractEvent<
      WeightsUpdatedEvent.InputTuple,
      WeightsUpdatedEvent.OutputTuple,
      WeightsUpdatedEvent.OutputObject
    >;
    WeightsUpdated: TypedContractEvent<
      WeightsUpdatedEvent.InputTuple,
      WeightsUpdatedEvent.OutputTuple,
      WeightsUpdatedEvent.OutputObject
    >;
  };
}
