/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface BindrGachaInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "NFT"
      | "NUM_BUCKETS"
      | "NUM_PACK_TIERS"
      | "WEIGHT_TOTAL_BPS"
      | "addCards"
      | "availableInBucket"
      | "availableInPack"
      | "backendSigner"
      | "cards"
      | "getBucketWeights"
      | "giveaway"
      | "owner"
      | "paused"
      | "polygonGiveawayUsed"
      | "pull"
      | "removeCard"
      | "renounceOwnership"
      | "setBackendSigner"
      | "setBucketWeights"
      | "setPaused"
      | "setVault"
      | "solanaGiveawayUsed"
      | "transferOwnership"
      | "vault"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BackendSignerChanged"
      | "CardAdded"
      | "CardRemoved"
      | "Giveaway"
      | "OwnershipTransferred"
      | "Paused"
      | "Pulled"
      | "Unpaused"
      | "VaultChanged"
      | "WeightsUpdated"
  ): EventFragment;

  encodeFunctionData(functionFragment: "NFT", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "NUM_BUCKETS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "NUM_PACK_TIERS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "WEIGHT_TOTAL_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addCards",
    values: [BigNumberish, BigNumberish[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "availableInBucket",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "availableInPack",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "backendSigner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cards",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBucketWeights",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "giveaway",
    values: [AddressLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "polygonGiveawayUsed",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "pull",
    values: [AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeCard",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setBackendSigner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setBucketWeights",
    values: [BigNumberish, BigNumberish[]]
  ): string;
  encodeFunctionData(functionFragment: "setPaused", values: [boolean]): string;
  encodeFunctionData(
    functionFragment: "setVault",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "solanaGiveawayUsed",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "vault", values?: undefined): string;

  decodeFunctionResult(functionFragment: "NFT", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "NUM_BUCKETS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "NUM_PACK_TIERS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "WEIGHT_TOTAL_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addCards", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "availableInBucket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "availableInPack",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "backendSigner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "cards", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getBucketWeights",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "giveaway", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "polygonGiveawayUsed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pull", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "removeCard", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBackendSigner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBucketWeights",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setPaused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setVault", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "solanaGiveawayUsed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vault", data: BytesLike): Result;
}

export namespace BackendSignerChangedEvent {
  export type InputTuple = [previous: AddressLike, current: AddressLike];
  export type OutputTuple = [previous: string, current: string];
  export interface OutputObject {
    previous: string;
    current: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CardAddedEvent {
  export type InputTuple = [
    packTier: BigNumberish,
    tokenId: BigNumberish,
    bucket: BigNumberish
  ];
  export type OutputTuple = [packTier: bigint, tokenId: bigint, bucket: bigint];
  export interface OutputObject {
    packTier: bigint;
    tokenId: bigint;
    bucket: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CardRemovedEvent {
  export type InputTuple = [packTier: BigNumberish, tokenId: BigNumberish];
  export type OutputTuple = [packTier: bigint, tokenId: bigint];
  export interface OutputObject {
    packTier: bigint;
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GiveawayEvent {
  export type InputTuple = [
    user: AddressLike,
    packTier: BigNumberish,
    tokenId: BigNumberish,
    bucket: BigNumberish,
    solanaHash: BytesLike
  ];
  export type OutputTuple = [
    user: string,
    packTier: bigint,
    tokenId: bigint,
    bucket: bigint,
    solanaHash: string
  ];
  export interface OutputObject {
    user: string;
    packTier: bigint;
    tokenId: bigint;
    bucket: bigint;
    solanaHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PulledEvent {
  export type InputTuple = [
    user: AddressLike,
    packTier: BigNumberish,
    tokenId: BigNumberish,
    bucket: BigNumberish,
    burnProof: BytesLike
  ];
  export type OutputTuple = [
    user: string,
    packTier: bigint,
    tokenId: bigint,
    bucket: bigint,
    burnProof: string
  ];
  export interface OutputObject {
    user: string;
    packTier: bigint;
    tokenId: bigint;
    bucket: bigint;
    burnProof: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VaultChangedEvent {
  export type InputTuple = [previous: AddressLike, current: AddressLike];
  export type OutputTuple = [previous: string, current: string];
  export interface OutputObject {
    previous: string;
    current: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WeightsUpdatedEvent {
  export type InputTuple = [packTier: BigNumberish, weights: BigNumberish[]];
  export type OutputTuple = [packTier: bigint, weights: bigint[]];
  export interface OutputObject {
    packTier: bigint;
    weights: bigint[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BindrGacha extends BaseContract {
  connect(runner?: ContractRunner | null): BindrGacha;
  waitForDeployment(): Promise<this>;

  interface: BindrGachaInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  NFT: TypedContractMethod<[], [string], "view">;

  NUM_BUCKETS: TypedContractMethod<[], [bigint], "view">;

  NUM_PACK_TIERS: TypedContractMethod<[], [bigint], "view">;

  WEIGHT_TOTAL_BPS: TypedContractMethod<[], [bigint], "view">;

  addCards: TypedContractMethod<
    [packTier: BigNumberish, tokenIds: BigNumberish[], buckets: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  availableInBucket: TypedContractMethod<
    [packTier: BigNumberish, bucket: BigNumberish],
    [bigint],
    "view"
  >;

  availableInPack: TypedContractMethod<
    [packTier: BigNumberish],
    [bigint],
    "view"
  >;

  backendSigner: TypedContractMethod<[], [string], "view">;

  cards: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [[bigint, boolean] & { bucket: bigint; available: boolean }],
    "view"
  >;

  getBucketWeights: TypedContractMethod<
    [packTier: BigNumberish],
    [bigint[]],
    "view"
  >;

  giveaway: TypedContractMethod<
    [user: AddressLike, solanaHash: BytesLike, packTier: BigNumberish],
    [[bigint, bigint] & { tokenId: bigint; bucket: bigint }],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  paused: TypedContractMethod<[], [boolean], "view">;

  polygonGiveawayUsed: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  pull: TypedContractMethod<
    [user: AddressLike, packTier: BigNumberish, burnProof: BytesLike],
    [[bigint, bigint] & { tokenId: bigint; bucket: bigint }],
    "nonpayable"
  >;

  removeCard: TypedContractMethod<
    [packTier: BigNumberish, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setBackendSigner: TypedContractMethod<
    [newSigner: AddressLike],
    [void],
    "nonpayable"
  >;

  setBucketWeights: TypedContractMethod<
    [packTier: BigNumberish, weights: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  setPaused: TypedContractMethod<[paused_: boolean], [void], "nonpayable">;

  setVault: TypedContractMethod<[newVault: AddressLike], [void], "nonpayable">;

  solanaGiveawayUsed: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  vault: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "NFT"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "NUM_BUCKETS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "NUM_PACK_TIERS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "WEIGHT_TOTAL_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "addCards"
  ): TypedContractMethod<
    [packTier: BigNumberish, tokenIds: BigNumberish[], buckets: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "availableInBucket"
  ): TypedContractMethod<
    [packTier: BigNumberish, bucket: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "availableInPack"
  ): TypedContractMethod<[packTier: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "backendSigner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "cards"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [[bigint, boolean] & { bucket: bigint; available: boolean }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getBucketWeights"
  ): TypedContractMethod<[packTier: BigNumberish], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "giveaway"
  ): TypedContractMethod<
    [user: AddressLike, solanaHash: BytesLike, packTier: BigNumberish],
    [[bigint, bigint] & { tokenId: bigint; bucket: bigint }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "polygonGiveawayUsed"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "pull"
  ): TypedContractMethod<
    [user: AddressLike, packTier: BigNumberish, burnProof: BytesLike],
    [[bigint, bigint] & { tokenId: bigint; bucket: bigint }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "removeCard"
  ): TypedContractMethod<
    [packTier: BigNumberish, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setBackendSigner"
  ): TypedContractMethod<[newSigner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setBucketWeights"
  ): TypedContractMethod<
    [packTier: BigNumberish, weights: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setPaused"
  ): TypedContractMethod<[paused_: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setVault"
  ): TypedContractMethod<[newVault: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "solanaGiveawayUsed"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "vault"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "BackendSignerChanged"
  ): TypedContractEvent<
    BackendSignerChangedEvent.InputTuple,
    BackendSignerChangedEvent.OutputTuple,
    BackendSignerChangedEvent.OutputObject
  >;
  getEvent(
    key: "CardAdded"
  ): TypedContractEvent<
    CardAddedEvent.InputTuple,
    CardAddedEvent.OutputTuple,
    CardAddedEvent.OutputObject
  >;
  getEvent(
    key: "CardRemoved"
  ): TypedContractEvent<
    CardRemovedEvent.InputTuple,
    CardRemovedEvent.OutputTuple,
    CardRemovedEvent.OutputObject
  >;
  getEvent(
    key: "Giveaway"
  ): TypedContractEvent<
    GiveawayEvent.InputTuple,
    GiveawayEvent.OutputTuple,
    GiveawayEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "Pulled"
  ): TypedContractEvent<
    PulledEvent.InputTuple,
    PulledEvent.OutputTuple,
    PulledEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;
  getEvent(
    key: "VaultChanged"
  ): TypedContractEvent<
    VaultChangedEvent.InputTuple,
    VaultChangedEvent.OutputTuple,
    VaultChangedEvent.OutputObject
  >;
  getEvent(
    key: "WeightsUpdated"
  ): TypedContractEvent<
    WeightsUpdatedEvent.InputTuple,
    WeightsUpdatedEvent.OutputTuple,
    WeightsUpdatedEvent.OutputObject
  >;

  filters: {
    "BackendSignerChanged(address,address)": TypedContractEvent<
      BackendSignerChangedEvent.InputTuple,
      BackendSignerChangedEvent.OutputTuple,
      BackendSignerChangedEvent.OutputObject
    >;
    BackendSignerChanged: TypedContractEvent<
      BackendSignerChangedEvent.InputTuple,
      BackendSignerChangedEvent.OutputTuple,
      BackendSignerChangedEvent.OutputObject
    >;

    "CardAdded(uint8,uint256,uint8)": TypedContractEvent<
      CardAddedEvent.InputTuple,
      CardAddedEvent.OutputTuple,
      CardAddedEvent.OutputObject
    >;
    CardAdded: TypedContractEvent<
      CardAddedEvent.InputTuple,
      CardAddedEvent.OutputTuple,
      CardAddedEvent.OutputObject
    >;

    "CardRemoved(uint8,uint256)": TypedContractEvent<
      CardRemovedEvent.InputTuple,
      CardRemovedEvent.OutputTuple,
      CardRemovedEvent.OutputObject
    >;
    CardRemoved: TypedContractEvent<
      CardRemovedEvent.InputTuple,
      CardRemovedEvent.OutputTuple,
      CardRemovedEvent.OutputObject
    >;

    "Giveaway(address,uint8,uint256,uint8,bytes32)": TypedContractEvent<
      GiveawayEvent.InputTuple,
      GiveawayEvent.OutputTuple,
      GiveawayEvent.OutputObject
    >;
    Giveaway: TypedContractEvent<
      GiveawayEvent.InputTuple,
      GiveawayEvent.OutputTuple,
      GiveawayEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "Pulled(address,uint8,uint256,uint8,bytes32)": TypedContractEvent<
      PulledEvent.InputTuple,
      PulledEvent.OutputTuple,
      PulledEvent.OutputObject
    >;
    Pulled: TypedContractEvent<
      PulledEvent.InputTuple,
      PulledEvent.OutputTuple,
      PulledEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;

    "VaultChanged(address,address)": TypedContractEvent<
      VaultChangedEvent.InputTuple,
      VaultChangedEvent.OutputTuple,
      VaultChangedEvent.OutputObject
    >;
    VaultChanged: TypedContractEvent<
      VaultChangedEvent.InputTuple,
      VaultChangedEvent.OutputTuple,
      VaultChangedEvent.OutputObject
    >;

    "WeightsUpdated(uint8,uint16[6])": TypedContractEvent<
      WeightsUpdatedEvent.InputTuple,
      WeightsUpdatedEvent.OutputTuple,
      WeightsUpdatedEvent.OutputObject
    >;
    WeightsUpdated: TypedContractEvent<
      WeightsUpdatedEvent.InputTuple,
      WeightsUpdatedEvent.OutputTuple,
      WeightsUpdatedEvent.OutputObject
    >;
  };
}
