/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as test from "./test";
export type { test };
export type { BindrGacha } from "./BindrGacha";
export type { BindrGachaV2 } from "./BindrGachaV2";
